target := "../../target"

health:
    cargo build --release --target=wasm32-unknown-unknown --features certora

integrity:
    cargo build --release --target=wasm32-unknown-unknown --no-default-features --features certora_nonhealth

other:
    cargo build --release --target=wasm32-unknown-unknown --no-default-features --features certora_nonhealth
    
clean:
    rm -rf {{target}}